### ISSUE TITLE
Repo description contains a typo "HasiCorp" -> "HashiCorp"

### ISSUE THREAD

**Issue by malt3** [tink-crypto/tink-go-hcvault#1]
**Describe the bug:**

Repo description contains a typo "HasiCorp" -> "HashiCorp"

**What was the expected behavior?**

I expected the description to read

```
Extension to Tink Go that provides HashiCorp Vault integration
```

**How can we reproduce the bug?**

n/a

**Do you have any debugging information?**

n/a

**What version of Tink are you using?**

n/a

**Can you tell us more about your development environment?**

n/a

**Comment by tholenst** [comment]
Thank you. I fixed it.
